### ISSUE TITLE
Pod microcks-async-minion not started

### ISSUE THREAD

**Issue by prabagodelrio** [microcks/microcks-ansible-operator#115]
### Describe the bug

I'm encountering an issue while attempting to start the microcks-async-minion pod in a Minikube environment following the installation steps [https://microcks.io/documentation/installing/operator/](url) provided for microcks-ansible-operator. After completing all necessary steps for installation, the microcks-async-minion pod fails to start properly and throws the following error:

`exec java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:+ExitOnOutOfMemoryError -cp .:/deployments/* io.quarkus.runner.GeneratedMain
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-05-29 10:32:13,627 INFO  [io.und.websockets] (main) UT026003: Adding annotated server endpoint class io.github.microcks.minion.async.producer.WebSocketProducerManagerSub2 for path /api/ws/{service}/{version}/{path}/{sub}
2024-05-29 10:32:13,663 INFO  [io.und.websockets] (main) UT026003: Adding annotated server endpoint class io.github.microcks.minion.async.producer.WebSocketProducerManagerSub3 for path /api/ws/{service}/{version}/{path}/{sub}/{sub2}
2024-05-29 10:32:13,674 INFO  [io.und.websockets] (main) UT026004: Adding annotated client endpoint class io.github.microcks.minion.async.consumer.WebSocketClient
2024-05-29 10:32:13,679 INFO  [io.und.websockets] (main) UT026003: Adding annotated server endpoint class io.github.microcks.minion.async.producer.WebSocketProducerManagerSub6 for path /api/ws/{service}/{version}/{path}/{sub}/{sub2}/{sub3}/{sub4}/{sub6}
2024-05-29 10:32:13,688 INFO  [io.und.websockets] (main) UT026003: Adding annotated server endpoint class io.github.microcks.minion.async.producer.WebSocketProducerManagerRoot for path /api/ws/{service}/{version}/
2024-05-29 10:32:13,693 INFO  [io.und.websockets] (main) UT026003: Adding annotated server endpoint class io.github.microcks.minion.async.producer.WebSocketProducerManagerSub4 for path /api/ws/{service}/{version}/{path}/{sub}/{sub2}/{sub3}
2024-05-29 10:32:13,697 INFO  [io.und.websockets] (main) UT026003: Adding annotated server endpoint class io.github.microcks.minion.async.producer.WebSocketProducerManagerSub5 for path /api/ws/{service}/{version}/{path}/{sub}/{sub2}/{sub3}/{sub4}
2024-05-29 10:32:13,700 INFO  [io.und.websockets] (main) UT026003: Adding annotated server endpoint class io.github.microcks.minion.async.producer.WebSocketProducerManagerSub for path /api/ws/{service}/{version}/{path}
2024-05-29 10:32:15,313 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18229: Configured topics for channel 'microcks-services-updates': [microcks-services-updates]
2024-05-29 10:32:15,917 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-consumer-thread-0) SRMSG18257: Kafka consumer kafka-consumer-microcks-services-updates, connected to Kafka brokers 'microcks-kafka-kafka-bootstrap:9092', belongs to the 'microcks-async-minion' consumer group and is configured to poll records from [microcks-services-updates]
2024-05-29 10:32:16,933 INFO  [io.git.mic.min.asy.AsyncMinionApp] (main) Microcks Keycloak server url {https://microcks-keycloak.192.168.59.100.nip.io} and realm {microcks}
2024-05-29 10:32:17,362 INFO  [io.git.mic.min.asy.AsyncMinionApp] (main) Authentication to Keycloak server succeed!
2024-05-29 10:32:18,985 WARN  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-microcks-services-updates, groupId=microcks-async-minion] Close timed out with 2 pending requests to coordinator, terminating client connections
2024-05-29 10:32:19,307 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [kube]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: jakarta.ws.rs.WebApplicationException: Unknown error, status code 500
	at org.jboss.resteasy.microprofile.client.DefaultResponseExceptionMapper.toThrowable(DefaultResponseExceptionMapper.java:42)
	at org.jboss.resteasy.microprofile.client.ExceptionMapping$HandlerException.mapException(ExceptionMapping.java:60)
	at io.quarkus.restclient.runtime.QuarkusProxyInvocationHandler.invoke(QuarkusProxyInvocationHandler.java:172)
	at jdk.proxy2/jdk.proxy2.$Proxy44.listServices(Unknown Source)
	at io.github.microcks.minion.async.AsyncMinionApp.onStart(AsyncMinionApp.java:113)
	at io.github.microcks.minion.async.AsyncMinionApp_Observer_onStart_6mlk52Ovj7Vk0r6BmDI2zOS9Ykg.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:157)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:108)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 7 more`

This error appears to indicate a problem during the startup of the Quarkus application within the pod. It seems to be related to a web application exception (jakarta.ws.rs.WebApplicationException) with a status code 500.

To address this issue, we would need to further investigate the root cause of the error. I would appreciate any guidance or additional assistance in resolving this problem and getting the microcks-async-minion pod to start successfully.

![image](https://github.com/microcks/microcks-ansible-operator/assets/25517820/851e8681-36f4-460a-88e6-3e9dfbbe3bd0)
![image](https://github.com/microcks/microcks-ansible-operator/assets/25517820/3e72bd2e-b19a-4bcf-9d23-21d5fb1e417c)

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

operator, minikube

**Comment by lbroudoux** [comment]
Hello! Sorry for delay in response. 
Have you checked if you any logs in the main Microcks pod logs at time of invocation? It looks like the main webapp pod is returning an error 500 when fetching the list of service to mock... I suspect that you may use the embedded Keycloak instance .... Have you tried to setup the `keycloak.privateUrl` parameter in the MicrocksInstall CR? This one is required if you're using generated certificates on your Keycloak.
